//variables

const copy=document.getElementById("copy");
const geneRator=document.getElementById("gen");
const text=document.getElementById("para");
let textCopied="";
async function getRandomParagraph() {
  const res = await fetch("https://baconipsum.com/api/?type=all-meat&paras=1");
  return await res.text();
};
//functions
//when the copy button is pressed the inenrtext of the whole para should be copied to thr clipboard of the user and it dhould be pastable 

copy.addEventListener("click",()=>{
   textCopied= text.innerText;
   navigator.clipboard.writeText(textCopied)
   .then(()=>(alert("This text is copied to the clipboard")))
})

//when the generate button is clicked the number shown on the input (the innertext of the input ) that many paras should be generated by the create element feature and they should all ahve the text of lorem but all differnt paragraphs 

//we have to generate different lorem paragraphs at all times
geneRator.addEventListener("click",async()=>{
    const numBer=Number(inputNum.value);
    //make a new element =the p tag *to the numBer
    text.innerHTML=""
    for(var i=0;i<numBer;i++){
        
        const newParas=  document.createElement("p");
 text.append(newParas);
    newParas.innerText= await getRandomParagraph();
      
    }
  
  
    //each line should be in a differnet paragraph 
})

